version: '3.7'

services:
  pulp:
    image: pulp/pulp:latest
    container_name: pulp_server
    ports:
      - "${PULP_HTTPS_PORT:-8080}:80"
    volumes:
      - pulp_storage:/var/lib/pulp
      - pulp_pgsql:/var/lib/pgsql
      - pulp_containers:/var/lib/containers
    restart: unless-stopped

volumes:
  pulp_storage:
  pulp_pgsql:
  pulp_containers: