from __future__ import annotations

import gzip
import io
import json
import tarfile
from pathlib import Path
from typing import BinaryIO, cast

import pytest
from pulp_harness.generate_deb_fixture import (
    FixtureRequest,
    ar_member,
    build_deb,
    generate_fixture,
    hash_block,
    main,
    parse_args,
    sha256,
    tar_gz,
)


def fixture_request(root: Path, metadata: Path) -> FixtureRequest:
    return FixtureRequest(
        repo_root=root,
        package="pulp-smoke",
        version="0.1.0",
        architecture="amd64",
        distribution="stable",
        component="main",
        summary="Disposable package generated by the local Pulp harness.",
        metadata=metadata,
    )


def test_ar_member_formats_header_and_padding_branches() -> None:
    even_member = ar_member("short", b"even")
    odd_long_member = ar_member("sixteen-byte-name", b"odd")

    assert even_member.startswith(b"short           0")
    assert even_member.endswith(b"even")
    assert odd_long_member.startswith(b"sixteen-byte-name/0")
    assert odd_long_member.endswith(b"odd\n")


def test_tar_gz_is_deterministic_and_contains_expected_files() -> None:
    archive_a = tar_gz({"./usr/": b"", "./usr/share/pulp-smoke/message.txt": b"payload"})
    archive_b = tar_gz({"./usr/": b"", "./usr/share/pulp-smoke/message.txt": b"payload"})

    assert archive_a == archive_b
    with (
        gzip.GzipFile(fileobj=io.BytesIO(archive_a), mode="rb") as gzip_handle,
        tarfile.open(fileobj=cast(BinaryIO, gzip_handle), mode="r|") as archive,
    ):
        members = archive.getmembers()

    assert [member.name for member in members] == ["./usr", "./usr/share/pulp-smoke/message.txt"]
    assert members[0].mtime == 0
    assert members[0].uname == "root"
    assert members[0].isdir()
    assert members[0].mode == 0o755
    assert members[1].isfile()
    assert members[1].mode == 0o644


def test_build_deb_is_deterministic_and_uses_expected_members() -> None:
    deb_a = build_deb("pulp-smoke", "0.1.0", "amd64", "summary")
    deb_b = build_deb("pulp-smoke", "0.1.0", "amd64", "summary")

    assert deb_a == deb_b
    assert deb_a.startswith(b"!<arch>\n")
    assert b"debian-binary" in deb_a
    assert b"control.tar.gz" in deb_a
    assert b"data.tar.gz" in deb_a


def test_generate_fixture_writes_repository_indexes_and_metadata(tmp_path: Path) -> None:
    metadata_path = tmp_path / "metadata.json"
    request = fixture_request(tmp_path / "repo", metadata_path)

    metadata = generate_fixture(request)

    deb_path = Path(metadata["deb"]["path"])
    packages_path = request.repo_root / "dists/stable/main/binary-amd64/Packages"
    release_path = request.repo_root / "dists/stable/Release"
    metadata_from_disk = json.loads(metadata_path.read_text(encoding="utf-8"))

    assert deb_path.exists()
    assert metadata_from_disk == metadata
    assert metadata["deb"]["sha256"] == sha256(deb_path)
    assert "Filename: pool/main/p/pulp-smoke/pulp-smoke_0.1.0_amd64.deb" in packages_path.read_text(
        encoding="utf-8",
    )
    assert "SHA256:" in release_path.read_text(encoding="utf-8")


def test_hash_block_uses_requested_algorithm_and_relative_paths(tmp_path: Path) -> None:
    root = tmp_path / "root"
    child = root / "nested" / "index.txt"
    child.parent.mkdir(parents=True)
    child.write_text("payload", encoding="utf-8")

    block = hash_block([child], root, "sha256")

    assert block.endswith(" nested/index.txt")
    assert "239f59ed55e737c77147cf55ad0c1b030b6d7ee748a7426952f9b852d5a935e5" in block


def test_parse_args_returns_typed_fixture_request(tmp_path: Path) -> None:
    request = parse_args(
        [
            "--repo-root",
            str(tmp_path / "repo"),
            "--package",
            "pulp-smoke",
            "--version",
            "0.1.0",
            "--architecture",
            "amd64",
            "--distribution",
            "stable",
            "--component",
            "main",
            "--summary",
            "summary",
            "--metadata",
            str(tmp_path / "metadata.json"),
        ],
    )

    assert request.repo_root == tmp_path / "repo"
    assert request.package == "pulp-smoke"
    assert request.metadata == tmp_path / "metadata.json"


def test_main_writes_metadata_and_prints_json(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    metadata_path = tmp_path / "metadata.json"

    exit_code = main(
        [
            "--repo-root",
            str(tmp_path / "repo"),
            "--package",
            "pulp-smoke",
            "--version",
            "0.1.0",
            "--architecture",
            "amd64",
            "--distribution",
            "stable",
            "--component",
            "main",
            "--summary",
            "summary",
            "--metadata",
            str(metadata_path),
        ],
    )
    captured = capsys.readouterr()

    assert exit_code == 0
    assert metadata_path.exists()
    assert json.loads(captured.out)["package"] == "pulp-smoke"
