#!/usr/bin/env bash
set -euo pipefail

# shellcheck source=harness/local/scripts/common.sh
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/common.sh"

require_cmd python3

log "checking shell syntax"
bash -n "${SCRIPT_DIR}"/*.sh "${REPO_ROOT}/tests/e2e/pulp-local-apt-smoke.sh"

log "checking Python syntax"
python3 -m py_compile "${SCRIPT_DIR}/generate-deb-fixture.py"
python3 -m py_compile "${HARNESS_DIR}/pulp_harness/__init__.py" "${HARNESS_DIR}/pulp_harness/generate_deb_fixture.py"

log "checking JSON files"
python3 -m json.tool "${REPO_ROOT}/schemas/pulp-solution.schema.json" >/dev/null
python3 -m json.tool "${REPO_ROOT}/solutions/local-apt-smoke.json" >/dev/null

log "checking solution contract"
python3 - "${REPO_ROOT}/solutions/local-apt-smoke.json" <<'PY'
import json
import sys
from pathlib import Path

solution = json.loads(Path(sys.argv[1]).read_text())
for key in ["name", "fixture", "apt", "pulp", "evidence"]:
    if key not in solution:
        raise SystemExit(f"missing required field: {key}")
for key in ["repositoryName", "remoteName", "publicationName", "distributionName", "requiredPlugins"]:
    if key not in solution["pulp"]:
        raise SystemExit(f"missing pulp field: {key}")
if "pulp_deb" not in solution["pulp"]["requiredPlugins"]:
    raise SystemExit("solution must require pulp_deb")
PY

fixture_root="${TMPDIR:-/tmp}/pulp-harness-static-fixture"
rm -rf "${fixture_root}"
mkdir -p "${fixture_root}"

log "checking deterministic apt fixture generation"
"${SCRIPT_DIR}/generate-deb-fixture.py" \
  --repo-root "${fixture_root}/repo-a" \
  --package pulp-smoke \
  --version 0.1.0 \
  --architecture amd64 \
  --distribution stable \
  --component main \
  --summary 'Disposable package generated by the local Pulp harness.' \
  --metadata "${fixture_root}/metadata-a.json" >/dev/null
"${SCRIPT_DIR}/generate-deb-fixture.py" \
  --repo-root "${fixture_root}/repo-b" \
  --package pulp-smoke \
  --version 0.1.0 \
  --architecture amd64 \
  --distribution stable \
  --component main \
  --summary 'Disposable package generated by the local Pulp harness.' \
  --metadata "${fixture_root}/metadata-b.json" >/dev/null
cmp "${fixture_root}/repo-a/dists/stable/Release" "${fixture_root}/repo-b/dists/stable/Release" >/dev/null
cmp "${fixture_root}/repo-a/dists/stable/main/binary-amd64/Packages.gz" "${fixture_root}/repo-b/dists/stable/main/binary-amd64/Packages.gz" >/dev/null

if command -v dpkg-deb >/dev/null 2>&1; then
  log "checking generated .deb metadata"
  dpkg-deb --info "${fixture_root}/repo-a/pool/main/p/pulp-smoke/pulp-smoke_0.1.0_amd64.deb" >/dev/null
else
  log "dpkg-deb unavailable; skipping package inspection"
fi

if command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; then
  log "checking Compose rendering with Docker Compose"
  PULP_IMAGE=pulp/pulp:3.21 \
  PULP_CONTAINER_NAME=pulp-local-apt-smoke \
  PULP_SESSION_DIR="${REPO_ROOT}/.runtime/pulp-sessions/local-apt-smoke" \
  PULP_HTTP_HOST_PORT=18080 \
  PULP_CONTAINER_HTTP_PORT=80 \
  PULP_PULL_POLICY=missing \
    docker compose -f "${HARNESS_DIR}/compose.pulp.yaml" config >/dev/null
elif command -v docker-compose >/dev/null 2>&1; then
  log "checking Compose rendering with docker-compose"
  PULP_IMAGE=pulp/pulp:3.21 \
  PULP_CONTAINER_NAME=pulp-local-apt-smoke \
  PULP_SESSION_DIR="${REPO_ROOT}/.runtime/pulp-sessions/local-apt-smoke" \
  PULP_HTTP_HOST_PORT=18080 \
  PULP_CONTAINER_HTTP_PORT=80 \
  PULP_PULL_POLICY=missing \
    docker-compose -f "${HARNESS_DIR}/compose.pulp.yaml" config >/dev/null
else
  log "Compose unavailable; skipping Compose rendering"
fi

log "static validation passed"
